linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - godot
    - goprintffuncname
    - nolintlint
    - revive
    - unconvert
    - unparam
    - whitespace
    - bodyclose
    - exportloopref
    - goconst
    - prealloc
    - predeclared
    - rowserrcheck
    - sqlclosecheck
    - stylecheck
    - tparallel
    - wastedassign

linters-settings:
  gocyclo:
    min-complexity: 30
  
  goconst:
    min-len: 3
    min-occurrences: 5
  
  misspell:
    locale: US
  
  revive:
    rules:
      - name: exported
        severity: warning
        disabled: false
      - name: var-naming
        severity: warning
        disabled: false
  
  gosec:
    excludes:
      - G306

issues:
  exclude-use-default: false
  max-issues-per-linter: 50
  max-same-issues: 10
  
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck
        - goconst
    - path: cmd/
      linters:
        - gocyclo
        - gosec
    - linters:
        - errcheck
      text: "Error return value of.*Close.*is not checked"

run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor
    - examples
  skip-files:
    - ".*\\.pb\\.go$"

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
