linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - godot
    - gocritic
    - goprintffuncname
    - nolintlint
    - revive
    - unconvert
    - unparam
    - whitespace
    - gocyclo
    - bodyclose
    - exportloopref
    - goconst
    - gomnd
    - gosec
    - prealloc
    - predeclared
    - rowserrcheck
    - sqlclosecheck
    - stylecheck
    - tparallel
    - unconvert
    - wastedassign

linters-settings:
  gocyclo:
    min-complexity: 15
  
  goconst:
    min-len: 3
    min-occurrences: 3
  
  misspell:
    locale: US
  
  revive:
    rules:
      - name: exported
        severity: warning
        disabled: false
      - name: var-naming
        severity: warning
        disabled: false
      - name: package-comments
        severity: warning
        disabled: false

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck
        - goconst

run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor
    - examples
  skip-files:
    - ".*\\.pb\\.go$"

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
